# Corrected Go pipeline
# Build your Go project.
# Learn more about Go in Azure Pipelines:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GOBIN:  '$(GOPATH)/bin'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(Build.Repository.Name)'

steps:
- task: GoTool@0
  displayName: 'Install Go 1.13.5'
  inputs:
    version: '1.13.5'

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
  displayName: 'Set up the Go workspace'

- script: |
    go version
    go get -v -t -d ./...
    go build -v .
    go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, build, and test'
  
- task: CopyFiles@2
  displayName: 'Copy build artifacts'
  inputs:
    SourceFolder: '$(modulePath)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
     artifactName: drop