trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.13.5'

- script: |
    # Set up the Go workspace and move code
    mkdir -p $(GOBIN) $(GOPATH)/pkg $(GOPATH)/src/github.com/$(Build.Repository.Name)
    mv !(gopath) $(GOPATH)/src/github.com/$(Build.Repository.Name)
    echo '##vso[task.prependpath]$(GOBIN)'
  displayName: 'Setup Go Workspace'
  env:
    GOPATH: '$(Agent.BuildDirectory)/gopath'
    GOBIN: '$(Agent.BuildDirectory)/gopath/bin'

- script: |
    # Get dependencies, build, and test
    go get -v -t -d ./...
    go build -v .
    go test -v ./...
  displayName: 'Build and Test'
  workingDirectory: '$(GOPATH)/src/github.com/$(Build.Repository.Name)'
  env:
    GOPATH: '$(Agent.BuildDirectory)/gopath'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    pathToPublish: '$(Agent.BuildDirectory)/gopath/src/github.com/$(Build.Repository.Name)'
  displayName: 'Publish Artifacts'